//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: copy_in.proto
namespace IronFoundry.WardenProtocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CopyInRequest")]
  public partial class CopyInRequest : global::ProtoBuf.IExtensible
  {
    public CopyInRequest() {}
    
    private string _handle;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"handle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string handle
    {
      get { return _handle; }
      set { _handle = value; }
    }
    private string _src_path;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"src_path", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string src_path
    {
      get { return _src_path; }
      set { _src_path = value; }
    }
    private string _dst_path;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"dst_path", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string dst_path
    {
      get { return _dst_path; }
      set { _dst_path = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CopyInResponse")]
  public partial class CopyInResponse : global::ProtoBuf.IExtensible
  {
    public CopyInResponse() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: copy_out.proto
namespace IronFoundry.WardenProtocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CopyOutRequest")]
  public partial class CopyOutRequest : global::ProtoBuf.IExtensible
  {
    public CopyOutRequest() {}
    
    private string _handle;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"handle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string handle
    {
      get { return _handle; }
      set { _handle = value; }
    }
    private string _src_path;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"src_path", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string src_path
    {
      get { return _src_path; }
      set { _src_path = value; }
    }
    private string _dst_path;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"dst_path", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string dst_path
    {
      get { return _dst_path; }
      set { _dst_path = value; }
    }

    private string _owner = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"owner", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string owner
    {
      get { return _owner; }
      set { _owner = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CopyOutResponse")]
  public partial class CopyOutResponse : global::ProtoBuf.IExtensible
  {
    public CopyOutResponse() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: create.proto
namespace IronFoundry.WardenProtocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateRequest")]
  public partial class CreateRequest : global::ProtoBuf.IExtensible
  {
    public CreateRequest() {}
    
    private readonly global::System.Collections.Generic.List<CreateRequest.BindMount> _bind_mounts = new global::System.Collections.Generic.List<CreateRequest.BindMount>();
    [global::ProtoBuf.ProtoMember(1, Name=@"bind_mounts", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<CreateRequest.BindMount> bind_mounts
    {
      get { return _bind_mounts; }
    }
  

    private uint _grace_time = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"grace_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint grace_time
    {
      get { return _grace_time; }
      set { _grace_time = value; }
    }

    private string _handle = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"handle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string handle
    {
      get { return _handle; }
      set { _handle = value; }
    }

    private string _network = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"network", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string network
    {
      get { return _network; }
      set { _network = value; }
    }

    private string _rootfs = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"rootfs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string rootfs
    {
      get { return _rootfs; }
      set { _rootfs = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BindMount")]
  public partial class BindMount : global::ProtoBuf.IExtensible
  {
    public BindMount() {}
    
    private string _src_path;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"src_path", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string src_path
    {
      get { return _src_path; }
      set { _src_path = value; }
    }
    private string _dst_path;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"dst_path", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string dst_path
    {
      get { return _dst_path; }
      set { _dst_path = value; }
    }
    private CreateRequest.BindMount.Mode _mode;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"mode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public CreateRequest.BindMount.Mode mode
    {
      get { return _mode; }
      set { _mode = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Mode")]
    public enum Mode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"RO", Value=0)]
      RO = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RW", Value=1)]
      RW = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateResponse")]
  public partial class CreateResponse : global::ProtoBuf.IExtensible
  {
    public CreateResponse() {}
    
    private string _handle;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"handle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string handle
    {
      get { return _handle; }
      set { _handle = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: destroy.proto
namespace IronFoundry.WardenProtocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DestroyRequest")]
  public partial class DestroyRequest : global::ProtoBuf.IExtensible
  {
    public DestroyRequest() {}
    
    private string _handle;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"handle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string handle
    {
      get { return _handle; }
      set { _handle = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DestroyResponse")]
  public partial class DestroyResponse : global::ProtoBuf.IExtensible
  {
    public DestroyResponse() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: echo.proto
namespace IronFoundry.WardenProtocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EchoRequest")]
  public partial class EchoRequest : global::ProtoBuf.IExtensible
  {
    public EchoRequest() {}
    
    private string _message;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string message
    {
      get { return _message; }
      set { _message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EchoResponse")]
  public partial class EchoResponse : global::ProtoBuf.IExtensible
  {
    public EchoResponse() {}
    
    private string _message;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string message
    {
      get { return _message; }
      set { _message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: error.proto
namespace IronFoundry.WardenProtocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ErrorResponse")]
  public partial class ErrorResponse : global::ProtoBuf.IExtensible
  {
    public ErrorResponse() {}
    

    private string _message = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string message
    {
      get { return _message; }
      set { _message = value; }
    }

    private string _data = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string data
    {
      get { return _data; }
      set { _data = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _backtrace = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(3, Name=@"backtrace", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> backtrace
    {
      get { return _backtrace; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: info.proto
namespace IronFoundry.WardenProtocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"InfoRequest")]
  public partial class InfoRequest : global::ProtoBuf.IExtensible
  {
    public InfoRequest() {}
    
    private string _handle;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"handle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string handle
    {
      get { return _handle; }
      set { _handle = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"InfoResponse")]
  public partial class InfoResponse : global::ProtoBuf.IExtensible
  {
    public InfoResponse() {}
    

    private string _state = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string state
    {
      get { return _state; }
      set { _state = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _events = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(20, Name=@"events", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> events
    {
      get { return _events; }
    }
  

    private string _host_ip = "";
    [global::ProtoBuf.ProtoMember(30, IsRequired = false, Name=@"host_ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string host_ip
    {
      get { return _host_ip; }
      set { _host_ip = value; }
    }

    private string _container_ip = "";
    [global::ProtoBuf.ProtoMember(31, IsRequired = false, Name=@"container_ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string container_ip
    {
      get { return _container_ip; }
      set { _container_ip = value; }
    }

    private string _container_path = "";
    [global::ProtoBuf.ProtoMember(32, IsRequired = false, Name=@"container_path", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string container_path
    {
      get { return _container_path; }
      set { _container_path = value; }
    }

    private InfoResponse.MemoryStat _memory_stat = null;
    [global::ProtoBuf.ProtoMember(40, IsRequired = false, Name=@"memory_stat", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public InfoResponse.MemoryStat memory_stat
    {
      get { return _memory_stat; }
      set { _memory_stat = value; }
    }

    private InfoResponse.CpuStat _cpu_stat = null;
    [global::ProtoBuf.ProtoMember(41, IsRequired = false, Name=@"cpu_stat", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public InfoResponse.CpuStat cpu_stat
    {
      get { return _cpu_stat; }
      set { _cpu_stat = value; }
    }

    private InfoResponse.DiskStat _disk_stat = null;
    [global::ProtoBuf.ProtoMember(42, IsRequired = false, Name=@"disk_stat", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public InfoResponse.DiskStat disk_stat
    {
      get { return _disk_stat; }
      set { _disk_stat = value; }
    }

    private InfoResponse.BandwidthStat _bandwidth_stat = null;
    [global::ProtoBuf.ProtoMember(43, IsRequired = false, Name=@"bandwidth_stat", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public InfoResponse.BandwidthStat bandwidth_stat
    {
      get { return _bandwidth_stat; }
      set { _bandwidth_stat = value; }
    }
    private readonly global::System.Collections.Generic.List<ulong> _job_ids = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(44, Name=@"job_ids", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> job_ids
    {
      get { return _job_ids; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MemoryStat")]
  public partial class MemoryStat : global::ProtoBuf.IExtensible
  {
    public MemoryStat() {}
    

    private ulong _cache = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"cache", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong cache
    {
      get { return _cache; }
      set { _cache = value; }
    }

    private ulong _rss = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"rss", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong rss
    {
      get { return _rss; }
      set { _rss = value; }
    }

    private ulong _mapped_file = default(ulong);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"mapped_file", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong mapped_file
    {
      get { return _mapped_file; }
      set { _mapped_file = value; }
    }

    private ulong _pgpgin = default(ulong);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"pgpgin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong pgpgin
    {
      get { return _pgpgin; }
      set { _pgpgin = value; }
    }

    private ulong _pgpgout = default(ulong);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"pgpgout", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong pgpgout
    {
      get { return _pgpgout; }
      set { _pgpgout = value; }
    }

    private ulong _swap = default(ulong);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"swap", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong swap
    {
      get { return _swap; }
      set { _swap = value; }
    }

    private ulong _pgfault = default(ulong);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"pgfault", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong pgfault
    {
      get { return _pgfault; }
      set { _pgfault = value; }
    }

    private ulong _pgmajfault = default(ulong);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"pgmajfault", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong pgmajfault
    {
      get { return _pgmajfault; }
      set { _pgmajfault = value; }
    }

    private ulong _inactive_anon = default(ulong);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"inactive_anon", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong inactive_anon
    {
      get { return _inactive_anon; }
      set { _inactive_anon = value; }
    }

    private ulong _active_anon = default(ulong);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"active_anon", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong active_anon
    {
      get { return _active_anon; }
      set { _active_anon = value; }
    }

    private ulong _inactive_file = default(ulong);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"inactive_file", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong inactive_file
    {
      get { return _inactive_file; }
      set { _inactive_file = value; }
    }

    private ulong _active_file = default(ulong);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"active_file", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong active_file
    {
      get { return _active_file; }
      set { _active_file = value; }
    }

    private ulong _unevictable = default(ulong);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"unevictable", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong unevictable
    {
      get { return _unevictable; }
      set { _unevictable = value; }
    }

    private ulong _hierarchical_memory_limit = default(ulong);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"hierarchical_memory_limit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong hierarchical_memory_limit
    {
      get { return _hierarchical_memory_limit; }
      set { _hierarchical_memory_limit = value; }
    }

    private ulong _hierarchical_memsw_limit = default(ulong);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"hierarchical_memsw_limit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong hierarchical_memsw_limit
    {
      get { return _hierarchical_memsw_limit; }
      set { _hierarchical_memsw_limit = value; }
    }

    private ulong _total_cache = default(ulong);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"total_cache", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong total_cache
    {
      get { return _total_cache; }
      set { _total_cache = value; }
    }

    private ulong _total_rss = default(ulong);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"total_rss", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong total_rss
    {
      get { return _total_rss; }
      set { _total_rss = value; }
    }

    private ulong _total_mapped_file = default(ulong);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"total_mapped_file", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong total_mapped_file
    {
      get { return _total_mapped_file; }
      set { _total_mapped_file = value; }
    }

    private ulong _total_pgpgin = default(ulong);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"total_pgpgin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong total_pgpgin
    {
      get { return _total_pgpgin; }
      set { _total_pgpgin = value; }
    }

    private ulong _total_pgpgout = default(ulong);
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"total_pgpgout", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong total_pgpgout
    {
      get { return _total_pgpgout; }
      set { _total_pgpgout = value; }
    }

    private ulong _total_swap = default(ulong);
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"total_swap", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong total_swap
    {
      get { return _total_swap; }
      set { _total_swap = value; }
    }

    private ulong _total_pgfault = default(ulong);
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"total_pgfault", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong total_pgfault
    {
      get { return _total_pgfault; }
      set { _total_pgfault = value; }
    }

    private ulong _total_pgmajfault = default(ulong);
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"total_pgmajfault", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong total_pgmajfault
    {
      get { return _total_pgmajfault; }
      set { _total_pgmajfault = value; }
    }

    private ulong _total_inactive_anon = default(ulong);
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"total_inactive_anon", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong total_inactive_anon
    {
      get { return _total_inactive_anon; }
      set { _total_inactive_anon = value; }
    }

    private ulong _total_active_anon = default(ulong);
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"total_active_anon", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong total_active_anon
    {
      get { return _total_active_anon; }
      set { _total_active_anon = value; }
    }

    private ulong _total_inactive_file = default(ulong);
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"total_inactive_file", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong total_inactive_file
    {
      get { return _total_inactive_file; }
      set { _total_inactive_file = value; }
    }

    private ulong _total_active_file = default(ulong);
    [global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"total_active_file", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong total_active_file
    {
      get { return _total_active_file; }
      set { _total_active_file = value; }
    }

    private ulong _total_unevictable = default(ulong);
    [global::ProtoBuf.ProtoMember(28, IsRequired = false, Name=@"total_unevictable", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong total_unevictable
    {
      get { return _total_unevictable; }
      set { _total_unevictable = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CpuStat")]
  public partial class CpuStat : global::ProtoBuf.IExtensible
  {
    public CpuStat() {}
    

    private ulong _usage = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"usage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong usage
    {
      get { return _usage; }
      set { _usage = value; }
    }

    private ulong _user = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"user", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong user
    {
      get { return _user; }
      set { _user = value; }
    }

    private ulong _system = default(ulong);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"system", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong system
    {
      get { return _system; }
      set { _system = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DiskStat")]
  public partial class DiskStat : global::ProtoBuf.IExtensible
  {
    public DiskStat() {}
    

    private ulong _bytes_used = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"bytes_used", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong bytes_used
    {
      get { return _bytes_used; }
      set { _bytes_used = value; }
    }

    private ulong _inodes_used = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"inodes_used", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong inodes_used
    {
      get { return _inodes_used; }
      set { _inodes_used = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BandwidthStat")]
  public partial class BandwidthStat : global::ProtoBuf.IExtensible
  {
    public BandwidthStat() {}
    

    private ulong _in_rate = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"in_rate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong in_rate
    {
      get { return _in_rate; }
      set { _in_rate = value; }
    }

    private ulong _in_burst = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"in_burst", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong in_burst
    {
      get { return _in_burst; }
      set { _in_burst = value; }
    }

    private ulong _out_rate = default(ulong);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"out_rate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong out_rate
    {
      get { return _out_rate; }
      set { _out_rate = value; }
    }

    private ulong _out_burst = default(ulong);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"out_burst", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong out_burst
    {
      get { return _out_burst; }
      set { _out_burst = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: limit_bandwidth.proto
namespace IronFoundry.WardenProtocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LimitBandwidthRequest")]
  public partial class LimitBandwidthRequest : global::ProtoBuf.IExtensible
  {
    public LimitBandwidthRequest() {}
    
    private string _handle;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"handle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string handle
    {
      get { return _handle; }
      set { _handle = value; }
    }
    private ulong _rate;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"rate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong rate
    {
      get { return _rate; }
      set { _rate = value; }
    }
    private ulong _burst;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"burst", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong burst
    {
      get { return _burst; }
      set { _burst = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LimitBandwidthResponse")]
  public partial class LimitBandwidthResponse : global::ProtoBuf.IExtensible
  {
    public LimitBandwidthResponse() {}
    
    private ulong _rate;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"rate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong rate
    {
      get { return _rate; }
      set { _rate = value; }
    }
    private ulong _burst;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"burst", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong burst
    {
      get { return _burst; }
      set { _burst = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: limit_disk.proto
namespace IronFoundry.WardenProtocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LimitDiskRequest")]
  public partial class LimitDiskRequest : global::ProtoBuf.IExtensible
  {
    public LimitDiskRequest() {}
    
    private string _handle;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"handle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string handle
    {
      get { return _handle; }
      set { _handle = value; }
    }

    private ulong _block_limit = default(ulong);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"block_limit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong block_limit
    {
      get { return _block_limit; }
      set { _block_limit = value; }
    }

    private ulong _block = default(ulong);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"block", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong block
    {
      get { return _block; }
      set { _block = value; }
    }

    private ulong _block_soft = default(ulong);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"block_soft", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong block_soft
    {
      get { return _block_soft; }
      set { _block_soft = value; }
    }

    private ulong _block_hard = default(ulong);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"block_hard", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong block_hard
    {
      get { return _block_hard; }
      set { _block_hard = value; }
    }

    private ulong _inode_limit = default(ulong);
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"inode_limit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong inode_limit
    {
      get { return _inode_limit; }
      set { _inode_limit = value; }
    }

    private ulong _inode = default(ulong);
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"inode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong inode
    {
      get { return _inode; }
      set { _inode = value; }
    }

    private ulong _inode_soft = default(ulong);
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"inode_soft", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong inode_soft
    {
      get { return _inode_soft; }
      set { _inode_soft = value; }
    }

    private ulong _inode_hard = default(ulong);
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"inode_hard", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong inode_hard
    {
      get { return _inode_hard; }
      set { _inode_hard = value; }
    }

    private ulong _byte_limit = default(ulong);
    [global::ProtoBuf.ProtoMember(30, IsRequired = false, Name=@"byte_limit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong byte_limit
    {
      get { return _byte_limit; }
      set { _byte_limit = value; }
    }

    private ulong _byte = default(ulong);
    [global::ProtoBuf.ProtoMember(31, IsRequired = false, Name=@"byte", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong @byte
    {
      get { return _byte; }
      set { _byte = value; }
    }

    private ulong _byte_soft = default(ulong);
    [global::ProtoBuf.ProtoMember(32, IsRequired = false, Name=@"byte_soft", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong byte_soft
    {
      get { return _byte_soft; }
      set { _byte_soft = value; }
    }

    private ulong _byte_hard = default(ulong);
    [global::ProtoBuf.ProtoMember(33, IsRequired = false, Name=@"byte_hard", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong byte_hard
    {
      get { return _byte_hard; }
      set { _byte_hard = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LimitDiskResponse")]
  public partial class LimitDiskResponse : global::ProtoBuf.IExtensible
  {
    public LimitDiskResponse() {}
    

    private ulong _block_limit = default(ulong);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"block_limit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong block_limit
    {
      get { return _block_limit; }
      set { _block_limit = value; }
    }

    private ulong _block = default(ulong);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"block", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong block
    {
      get { return _block; }
      set { _block = value; }
    }

    private ulong _block_soft = default(ulong);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"block_soft", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong block_soft
    {
      get { return _block_soft; }
      set { _block_soft = value; }
    }

    private ulong _block_hard = default(ulong);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"block_hard", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong block_hard
    {
      get { return _block_hard; }
      set { _block_hard = value; }
    }

    private ulong _inode_limit = default(ulong);
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"inode_limit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong inode_limit
    {
      get { return _inode_limit; }
      set { _inode_limit = value; }
    }

    private ulong _inode = default(ulong);
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"inode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong inode
    {
      get { return _inode; }
      set { _inode = value; }
    }

    private ulong _inode_soft = default(ulong);
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"inode_soft", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong inode_soft
    {
      get { return _inode_soft; }
      set { _inode_soft = value; }
    }

    private ulong _inode_hard = default(ulong);
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"inode_hard", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong inode_hard
    {
      get { return _inode_hard; }
      set { _inode_hard = value; }
    }

    private ulong _byte_limit = default(ulong);
    [global::ProtoBuf.ProtoMember(30, IsRequired = false, Name=@"byte_limit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong byte_limit
    {
      get { return _byte_limit; }
      set { _byte_limit = value; }
    }

    private ulong _byte = default(ulong);
    [global::ProtoBuf.ProtoMember(31, IsRequired = false, Name=@"byte", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong @byte
    {
      get { return _byte; }
      set { _byte = value; }
    }

    private ulong _byte_soft = default(ulong);
    [global::ProtoBuf.ProtoMember(32, IsRequired = false, Name=@"byte_soft", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong byte_soft
    {
      get { return _byte_soft; }
      set { _byte_soft = value; }
    }

    private ulong _byte_hard = default(ulong);
    [global::ProtoBuf.ProtoMember(33, IsRequired = false, Name=@"byte_hard", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong byte_hard
    {
      get { return _byte_hard; }
      set { _byte_hard = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: limit_memory.proto
namespace IronFoundry.WardenProtocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LimitMemoryRequest")]
  public partial class LimitMemoryRequest : global::ProtoBuf.IExtensible
  {
    public LimitMemoryRequest() {}
    
    private string _handle;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"handle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string handle
    {
      get { return _handle; }
      set { _handle = value; }
    }

    private ulong _limit_in_bytes = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"limit_in_bytes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong limit_in_bytes
    {
      get { return _limit_in_bytes; }
      set { _limit_in_bytes = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LimitMemoryResponse")]
  public partial class LimitMemoryResponse : global::ProtoBuf.IExtensible
  {
    public LimitMemoryResponse() {}
    

    private ulong _limit_in_bytes = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"limit_in_bytes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong limit_in_bytes
    {
      get { return _limit_in_bytes; }
      set { _limit_in_bytes = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: link.proto
namespace IronFoundry.WardenProtocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LinkRequest")]
  public partial class LinkRequest : global::ProtoBuf.IExtensible
  {
    public LinkRequest() {}
    
    private string _handle;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"handle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string handle
    {
      get { return _handle; }
      set { _handle = value; }
    }
    private uint _job_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"job_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint job_id
    {
      get { return _job_id; }
      set { _job_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LinkResponse")]
  public partial class LinkResponse : global::ProtoBuf.IExtensible
  {
    public LinkResponse() {}
    

    private uint _exit_status = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"exit_status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint exit_status
    {
      get { return _exit_status; }
      set { _exit_status = value; }
    }

    private string _stdout = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"stdout", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string stdout
    {
      get { return _stdout; }
      set { _stdout = value; }
    }

    private string _stderr = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"stderr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string stderr
    {
      get { return _stderr; }
      set { _stderr = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: list.proto
namespace IronFoundry.WardenProtocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ListRequest")]
  public partial class ListRequest : global::ProtoBuf.IExtensible
  {
    public ListRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ListResponse")]
  public partial class ListResponse : global::ProtoBuf.IExtensible
  {
    public ListResponse() {}
    
    private readonly global::System.Collections.Generic.List<string> _handles = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(1, Name=@"handles", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> handles
    {
      get { return _handles; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: message.proto
namespace IronFoundry.WardenProtocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Message")]
  public partial class Message : global::ProtoBuf.IExtensible
  {
    public Message() {}
    
    private Message.Type _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public Message.Type type
    {
      get { return _type; }
      set { _type = value; }
    }
    private byte[] _payload;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"payload", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] payload
    {
      get { return _payload; }
      set { _payload = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Type")]
    public enum Type
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error", Value=1)]
      Error = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Create", Value=11)]
      Create = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Stop", Value=12)]
      Stop = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Destroy", Value=13)]
      Destroy = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Info", Value=14)]
      Info = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Spawn", Value=21)]
      Spawn = 21,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Link", Value=22)]
      Link = 22,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Run", Value=23)]
      Run = 23,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Stream", Value=24)]
      Stream = 24,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NetIn", Value=31)]
      NetIn = 31,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NetOut", Value=32)]
      NetOut = 32,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CopyIn", Value=41)]
      CopyIn = 41,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CopyOut", Value=42)]
      CopyOut = 42,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LimitMemory", Value=51)]
      LimitMemory = 51,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LimitDisk", Value=52)]
      LimitDisk = 52,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LimitBandwidth", Value=53)]
      LimitBandwidth = 53,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Ping", Value=91)]
      Ping = 91,
            
      [global::ProtoBuf.ProtoEnum(Name=@"List", Value=92)]
      List = 92,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Echo", Value=93)]
      Echo = 93
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: net_in.proto
namespace IronFoundry.WardenProtocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NetInRequest")]
  public partial class NetInRequest : global::ProtoBuf.IExtensible
  {
    public NetInRequest() {}
    
    private string _handle;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"handle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string handle
    {
      get { return _handle; }
      set { _handle = value; }
    }

    private uint _host_port = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"host_port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint host_port
    {
      get { return _host_port; }
      set { _host_port = value; }
    }

    private uint _container_port = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"container_port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint container_port
    {
      get { return _container_port; }
      set { _container_port = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NetInResponse")]
  public partial class NetInResponse : global::ProtoBuf.IExtensible
  {
    public NetInResponse() {}
    
    private uint _host_port;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"host_port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint host_port
    {
      get { return _host_port; }
      set { _host_port = value; }
    }
    private uint _container_port;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"container_port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint container_port
    {
      get { return _container_port; }
      set { _container_port = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: net_out.proto
namespace IronFoundry.WardenProtocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NetOutRequest")]
  public partial class NetOutRequest : global::ProtoBuf.IExtensible
  {
    public NetOutRequest() {}
    
    private string _handle;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"handle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string handle
    {
      get { return _handle; }
      set { _handle = value; }
    }

    private string _network = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"network", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string network
    {
      get { return _network; }
      set { _network = value; }
    }

    private uint _port = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint port
    {
      get { return _port; }
      set { _port = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NetOutResponse")]
  public partial class NetOutResponse : global::ProtoBuf.IExtensible
  {
    public NetOutResponse() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: ping.proto
namespace IronFoundry.WardenProtocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PingRequest")]
  public partial class PingRequest : global::ProtoBuf.IExtensible
  {
    public PingRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PingResponse")]
  public partial class PingResponse : global::ProtoBuf.IExtensible
  {
    public PingResponse() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: resource_limits.proto
namespace IronFoundry.WardenProtocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResourceLimits")]
  public partial class ResourceLimits : global::ProtoBuf.IExtensible
  {
    public ResourceLimits() {}
    

    private ulong _as = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"as", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong @as
    {
      get { return _as; }
      set { _as = value; }
    }

    private ulong _core = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"core", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong core
    {
      get { return _core; }
      set { _core = value; }
    }

    private ulong _cpu = default(ulong);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"cpu", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong cpu
    {
      get { return _cpu; }
      set { _cpu = value; }
    }

    private ulong _data = default(ulong);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong data
    {
      get { return _data; }
      set { _data = value; }
    }

    private ulong _fsize = default(ulong);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"fsize", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong fsize
    {
      get { return _fsize; }
      set { _fsize = value; }
    }

    private ulong _locks = default(ulong);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"locks", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong locks
    {
      get { return _locks; }
      set { _locks = value; }
    }

    private ulong _memlock = default(ulong);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"memlock", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong memlock
    {
      get { return _memlock; }
      set { _memlock = value; }
    }

    private ulong _msgqueue = default(ulong);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"msgqueue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong msgqueue
    {
      get { return _msgqueue; }
      set { _msgqueue = value; }
    }

    private ulong _nice = default(ulong);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"nice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong nice
    {
      get { return _nice; }
      set { _nice = value; }
    }

    private ulong _nofile = default(ulong);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"nofile", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong nofile
    {
      get { return _nofile; }
      set { _nofile = value; }
    }

    private ulong _nproc = default(ulong);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"nproc", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong nproc
    {
      get { return _nproc; }
      set { _nproc = value; }
    }

    private ulong _rss = default(ulong);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"rss", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong rss
    {
      get { return _rss; }
      set { _rss = value; }
    }

    private ulong _rtprio = default(ulong);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"rtprio", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong rtprio
    {
      get { return _rtprio; }
      set { _rtprio = value; }
    }

    private ulong _sigpending = default(ulong);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"sigpending", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong sigpending
    {
      get { return _sigpending; }
      set { _sigpending = value; }
    }

    private ulong _stack = default(ulong);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"stack", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong stack
    {
      get { return _stack; }
      set { _stack = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: run.proto
// Note: requires additional types generated from: resource_limits.proto
namespace IronFoundry.WardenProtocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RunRequest")]
  public partial class RunRequest : global::ProtoBuf.IExtensible
  {
    public RunRequest() {}
    
    private string _handle;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"handle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string handle
    {
      get { return _handle; }
      set { _handle = value; }
    }
    private string _script;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"script", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string script
    {
      get { return _script; }
      set { _script = value; }
    }

    private bool _privileged = (bool)false;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"privileged", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool privileged
    {
      get { return _privileged; }
      set { _privileged = value; }
    }

    private ResourceLimits _rlimits = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"rlimits", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ResourceLimits rlimits
    {
      get { return _rlimits; }
      set { _rlimits = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RunResponse")]
  public partial class RunResponse : global::ProtoBuf.IExtensible
  {
    public RunResponse() {}
    

    private uint _exit_status = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"exit_status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint exit_status
    {
      get { return _exit_status; }
      set { _exit_status = value; }
    }

    private string _stdout = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"stdout", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string stdout
    {
      get { return _stdout; }
      set { _stdout = value; }
    }

    private string _stderr = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"stderr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string stderr
    {
      get { return _stderr; }
      set { _stderr = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: spawn.proto
// Note: requires additional types generated from: resource_limits.proto
namespace IronFoundry.WardenProtocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SpawnRequest")]
  public partial class SpawnRequest : global::ProtoBuf.IExtensible
  {
    public SpawnRequest() {}
    
    private string _handle;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"handle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string handle
    {
      get { return _handle; }
      set { _handle = value; }
    }
    private string _script;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"script", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string script
    {
      get { return _script; }
      set { _script = value; }
    }

    private bool _privileged = (bool)false;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"privileged", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool privileged
    {
      get { return _privileged; }
      set { _privileged = value; }
    }

    private ResourceLimits _rlimits = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"rlimits", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ResourceLimits rlimits
    {
      get { return _rlimits; }
      set { _rlimits = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SpawnResponse")]
  public partial class SpawnResponse : global::ProtoBuf.IExtensible
  {
    public SpawnResponse() {}
    
    private uint _job_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"job_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint job_id
    {
      get { return _job_id; }
      set { _job_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: stop.proto
namespace IronFoundry.WardenProtocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StopRequest")]
  public partial class StopRequest : global::ProtoBuf.IExtensible
  {
    public StopRequest() {}
    
    private string _handle;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"handle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string handle
    {
      get { return _handle; }
      set { _handle = value; }
    }

    private bool _background = (bool)false;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"background", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool background
    {
      get { return _background; }
      set { _background = value; }
    }

    private bool _kill = (bool)false;
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"kill", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool kill
    {
      get { return _kill; }
      set { _kill = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StopResponse")]
  public partial class StopResponse : global::ProtoBuf.IExtensible
  {
    public StopResponse() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: stream.proto
namespace IronFoundry.WardenProtocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StreamRequest")]
  public partial class StreamRequest : global::ProtoBuf.IExtensible
  {
    public StreamRequest() {}
    
    private string _handle;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"handle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string handle
    {
      get { return _handle; }
      set { _handle = value; }
    }
    private uint _job_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"job_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint job_id
    {
      get { return _job_id; }
      set { _job_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StreamResponse")]
  public partial class StreamResponse : global::ProtoBuf.IExtensible
  {
    public StreamResponse() {}
    

    private string _name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }

    private string _data = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string data
    {
      get { return _data; }
      set { _data = value; }
    }

    private uint _exit_status = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"exit_status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint exit_status
    {
      get { return _exit_status; }
      set { _exit_status = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
