//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: copy_in.proto
namespace IronFoundry.Warden.Protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CopyInRequest")]
  public partial class CopyInRequest : global::ProtoBuf.IExtensible
  {
    public CopyInRequest() {}
    
    private string _handle;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"handle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Handle
    {
      get { return _handle; }
      set { _handle = value; }
    }
    private string _srcPath;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"src_path", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string SrcPath
    {
      get { return _srcPath; }
      set { _srcPath = value; }
    }
    private string _dstPath;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"dst_path", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string DstPath
    {
      get { return _dstPath; }
      set { _dstPath = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CopyInResponse")]
  public partial class CopyInResponse : global::ProtoBuf.IExtensible
  {
    public CopyInResponse() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: copy_out.proto
namespace IronFoundry.Warden.Protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CopyOutRequest")]
  public partial class CopyOutRequest : global::ProtoBuf.IExtensible
  {
    public CopyOutRequest() {}
    
    private string _handle;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"handle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Handle
    {
      get { return _handle; }
      set { _handle = value; }
    }
    private string _srcPath;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"src_path", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string SrcPath
    {
      get { return _srcPath; }
      set { _srcPath = value; }
    }
    private string _dstPath;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"dst_path", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string DstPath
    {
      get { return _dstPath; }
      set { _dstPath = value; }
    }

    private string _owner = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"owner", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Owner
    {
      get { return _owner; }
      set { _owner = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CopyOutResponse")]
  public partial class CopyOutResponse : global::ProtoBuf.IExtensible
  {
    public CopyOutResponse() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: create.proto
namespace IronFoundry.Warden.Protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateRequest")]
  public partial class CreateRequest : global::ProtoBuf.IExtensible
  {
    public CreateRequest() {}
    
    private readonly global::System.Collections.Generic.List<IronFoundry.Warden.Protocol.CreateRequest.BindMount> _bindMounts = new global::System.Collections.Generic.List<IronFoundry.Warden.Protocol.CreateRequest.BindMount>();
    [global::ProtoBuf.ProtoMember(1, Name=@"bind_mounts", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<IronFoundry.Warden.Protocol.CreateRequest.BindMount> BindMounts
    {
      get { return _bindMounts; }
    }
  

    private uint _graceTime = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"grace_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint GraceTime
    {
      get { return _graceTime; }
      set { _graceTime = value; }
    }

    private string _handle = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"handle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Handle
    {
      get { return _handle; }
      set { _handle = value; }
    }

    private string _network = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"network", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Network
    {
      get { return _network; }
      set { _network = value; }
    }

    private string _rootfs = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"rootfs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Rootfs
    {
      get { return _rootfs; }
      set { _rootfs = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BindMount")]
  public partial class BindMount : global::ProtoBuf.IExtensible
  {
    public BindMount() {}
    
    private string _srcPath;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"src_path", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string SrcPath
    {
      get { return _srcPath; }
      set { _srcPath = value; }
    }
    private string _dstPath;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"dst_path", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string DstPath
    {
      get { return _dstPath; }
      set { _dstPath = value; }
    }
    private IronFoundry.Warden.Protocol.CreateRequest.BindMount.Mode _bindMountMode;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"bind_mount_mode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public IronFoundry.Warden.Protocol.CreateRequest.BindMount.Mode BindMountMode
    {
      get { return _bindMountMode; }
      set { _bindMountMode = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Mode")]
    public enum Mode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"RO", Value=0)]
      RO = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RW", Value=1)]
      RW = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateResponse")]
  public partial class CreateResponse : global::ProtoBuf.IExtensible
  {
    public CreateResponse() {}
    
    private string _handle;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"handle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Handle
    {
      get { return _handle; }
      set { _handle = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: destroy.proto
namespace IronFoundry.Warden.Protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DestroyRequest")]
  public partial class DestroyRequest : global::ProtoBuf.IExtensible
  {
    public DestroyRequest() {}
    
    private string _handle;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"handle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Handle
    {
      get { return _handle; }
      set { _handle = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DestroyResponse")]
  public partial class DestroyResponse : global::ProtoBuf.IExtensible
  {
    public DestroyResponse() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: echo.proto
namespace IronFoundry.Warden.Protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EchoRequest")]
  public partial class EchoRequest : global::ProtoBuf.IExtensible
  {
    public EchoRequest() {}
    
    private string _message;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Message
    {
      get { return _message; }
      set { _message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EchoResponse")]
  public partial class EchoResponse : global::ProtoBuf.IExtensible
  {
    public EchoResponse() {}
    
    private string _message;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Message
    {
      get { return _message; }
      set { _message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: error.proto
namespace IronFoundry.Warden.Protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ErrorResponse")]
  public partial class ErrorResponse : global::ProtoBuf.IExtensible
  {
    public ErrorResponse() {}
    

    private string _message = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Message
    {
      get { return _message; }
      set { _message = value; }
    }

    private string _data = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Data
    {
      get { return _data; }
      set { _data = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _backtrace = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(3, Name=@"backtrace", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> Backtrace
    {
      get { return _backtrace; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: info.proto
namespace IronFoundry.Warden.Protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"InfoRequest")]
  public partial class InfoRequest : global::ProtoBuf.IExtensible
  {
    public InfoRequest() {}
    
    private string _handle;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"handle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Handle
    {
      get { return _handle; }
      set { _handle = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"InfoResponse")]
  public partial class InfoResponse : global::ProtoBuf.IExtensible
  {
    public InfoResponse() {}
    

    private string _state = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string State
    {
      get { return _state; }
      set { _state = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _events = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(20, Name=@"events", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> Events
    {
      get { return _events; }
    }
  

    private string _hostIp = "";
    [global::ProtoBuf.ProtoMember(30, IsRequired = false, Name=@"host_ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string HostIp
    {
      get { return _hostIp; }
      set { _hostIp = value; }
    }

    private string _containerIp = "";
    [global::ProtoBuf.ProtoMember(31, IsRequired = false, Name=@"container_ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ContainerIp
    {
      get { return _containerIp; }
      set { _containerIp = value; }
    }

    private string _containerPath = "";
    [global::ProtoBuf.ProtoMember(32, IsRequired = false, Name=@"container_path", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ContainerPath
    {
      get { return _containerPath; }
      set { _containerPath = value; }
    }

    private IronFoundry.Warden.Protocol.InfoResponse.MemoryStat _memoryStatInfo = null;
    [global::ProtoBuf.ProtoMember(40, IsRequired = false, Name=@"memory_stat_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public IronFoundry.Warden.Protocol.InfoResponse.MemoryStat MemoryStatInfo
    {
      get { return _memoryStatInfo; }
      set { _memoryStatInfo = value; }
    }

    private IronFoundry.Warden.Protocol.InfoResponse.CpuStat _cpuStatInfo = null;
    [global::ProtoBuf.ProtoMember(41, IsRequired = false, Name=@"cpu_stat_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public IronFoundry.Warden.Protocol.InfoResponse.CpuStat CpuStatInfo
    {
      get { return _cpuStatInfo; }
      set { _cpuStatInfo = value; }
    }

    private IronFoundry.Warden.Protocol.InfoResponse.DiskStat _diskStatInfo = null;
    [global::ProtoBuf.ProtoMember(42, IsRequired = false, Name=@"disk_stat_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public IronFoundry.Warden.Protocol.InfoResponse.DiskStat DiskStatInfo
    {
      get { return _diskStatInfo; }
      set { _diskStatInfo = value; }
    }

    private IronFoundry.Warden.Protocol.InfoResponse.BandwidthStat _bandwidthStatInfo = null;
    [global::ProtoBuf.ProtoMember(43, IsRequired = false, Name=@"bandwidth_stat_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public IronFoundry.Warden.Protocol.InfoResponse.BandwidthStat BandwidthStatInfo
    {
      get { return _bandwidthStatInfo; }
      set { _bandwidthStatInfo = value; }
    }
    private readonly global::System.Collections.Generic.List<ulong> _jobIds = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(44, Name=@"job_ids", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> JobIds
    {
      get { return _jobIds; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MemoryStat")]
  public partial class MemoryStat : global::ProtoBuf.IExtensible
  {
    public MemoryStat() {}
    

    private ulong _cache = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"cache", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong Cache
    {
      get { return _cache; }
      set { _cache = value; }
    }

    private ulong _rss = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"rss", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong Rss
    {
      get { return _rss; }
      set { _rss = value; }
    }

    private ulong _mappedFile = default(ulong);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"mapped_file", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong MappedFile
    {
      get { return _mappedFile; }
      set { _mappedFile = value; }
    }

    private ulong _pgpgin = default(ulong);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"pgpgin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong Pgpgin
    {
      get { return _pgpgin; }
      set { _pgpgin = value; }
    }

    private ulong _pgpgout = default(ulong);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"pgpgout", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong Pgpgout
    {
      get { return _pgpgout; }
      set { _pgpgout = value; }
    }

    private ulong _swap = default(ulong);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"swap", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong Swap
    {
      get { return _swap; }
      set { _swap = value; }
    }

    private ulong _pgfault = default(ulong);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"pgfault", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong Pgfault
    {
      get { return _pgfault; }
      set { _pgfault = value; }
    }

    private ulong _pgmajfault = default(ulong);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"pgmajfault", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong Pgmajfault
    {
      get { return _pgmajfault; }
      set { _pgmajfault = value; }
    }

    private ulong _inactiveAnon = default(ulong);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"inactive_anon", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong InactiveAnon
    {
      get { return _inactiveAnon; }
      set { _inactiveAnon = value; }
    }

    private ulong _activeAnon = default(ulong);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"active_anon", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong ActiveAnon
    {
      get { return _activeAnon; }
      set { _activeAnon = value; }
    }

    private ulong _inactiveFile = default(ulong);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"inactive_file", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong InactiveFile
    {
      get { return _inactiveFile; }
      set { _inactiveFile = value; }
    }

    private ulong _activeFile = default(ulong);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"active_file", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong ActiveFile
    {
      get { return _activeFile; }
      set { _activeFile = value; }
    }

    private ulong _unevictable = default(ulong);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"unevictable", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong Unevictable
    {
      get { return _unevictable; }
      set { _unevictable = value; }
    }

    private ulong _hierarchicalMemoryLimit = default(ulong);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"hierarchical_memory_limit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong HierarchicalMemoryLimit
    {
      get { return _hierarchicalMemoryLimit; }
      set { _hierarchicalMemoryLimit = value; }
    }

    private ulong _hierarchicalMemswLimit = default(ulong);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"hierarchical_memsw_limit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong HierarchicalMemswLimit
    {
      get { return _hierarchicalMemswLimit; }
      set { _hierarchicalMemswLimit = value; }
    }

    private ulong _totalCache = default(ulong);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"total_cache", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong TotalCache
    {
      get { return _totalCache; }
      set { _totalCache = value; }
    }

    private ulong _totalRss = default(ulong);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"total_rss", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong TotalRss
    {
      get { return _totalRss; }
      set { _totalRss = value; }
    }

    private ulong _totalMappedFile = default(ulong);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"total_mapped_file", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong TotalMappedFile
    {
      get { return _totalMappedFile; }
      set { _totalMappedFile = value; }
    }

    private ulong _totalPgpgin = default(ulong);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"total_pgpgin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong TotalPgpgin
    {
      get { return _totalPgpgin; }
      set { _totalPgpgin = value; }
    }

    private ulong _totalPgpgout = default(ulong);
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"total_pgpgout", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong TotalPgpgout
    {
      get { return _totalPgpgout; }
      set { _totalPgpgout = value; }
    }

    private ulong _totalSwap = default(ulong);
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"total_swap", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong TotalSwap
    {
      get { return _totalSwap; }
      set { _totalSwap = value; }
    }

    private ulong _totalPgfault = default(ulong);
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"total_pgfault", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong TotalPgfault
    {
      get { return _totalPgfault; }
      set { _totalPgfault = value; }
    }

    private ulong _totalPgmajfault = default(ulong);
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"total_pgmajfault", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong TotalPgmajfault
    {
      get { return _totalPgmajfault; }
      set { _totalPgmajfault = value; }
    }

    private ulong _totalInactiveAnon = default(ulong);
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"total_inactive_anon", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong TotalInactiveAnon
    {
      get { return _totalInactiveAnon; }
      set { _totalInactiveAnon = value; }
    }

    private ulong _totalActiveAnon = default(ulong);
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"total_active_anon", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong TotalActiveAnon
    {
      get { return _totalActiveAnon; }
      set { _totalActiveAnon = value; }
    }

    private ulong _totalInactiveFile = default(ulong);
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"total_inactive_file", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong TotalInactiveFile
    {
      get { return _totalInactiveFile; }
      set { _totalInactiveFile = value; }
    }

    private ulong _totalActiveFile = default(ulong);
    [global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"total_active_file", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong TotalActiveFile
    {
      get { return _totalActiveFile; }
      set { _totalActiveFile = value; }
    }

    private ulong _totalUnevictable = default(ulong);
    [global::ProtoBuf.ProtoMember(28, IsRequired = false, Name=@"total_unevictable", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong TotalUnevictable
    {
      get { return _totalUnevictable; }
      set { _totalUnevictable = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CpuStat")]
  public partial class CpuStat : global::ProtoBuf.IExtensible
  {
    public CpuStat() {}
    

    private ulong _usage = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"usage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong Usage
    {
      get { return _usage; }
      set { _usage = value; }
    }

    private ulong _user = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"user", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong User
    {
      get { return _user; }
      set { _user = value; }
    }

    private ulong _system = default(ulong);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"system", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong System
    {
      get { return _system; }
      set { _system = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DiskStat")]
  public partial class DiskStat : global::ProtoBuf.IExtensible
  {
    public DiskStat() {}
    

    private ulong _bytesUsed = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"bytes_used", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong BytesUsed
    {
      get { return _bytesUsed; }
      set { _bytesUsed = value; }
    }

    private ulong _inodesUsed = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"inodes_used", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong InodesUsed
    {
      get { return _inodesUsed; }
      set { _inodesUsed = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BandwidthStat")]
  public partial class BandwidthStat : global::ProtoBuf.IExtensible
  {
    public BandwidthStat() {}
    

    private ulong _inRate = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"in_rate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong InRate
    {
      get { return _inRate; }
      set { _inRate = value; }
    }

    private ulong _inBurst = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"in_burst", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong InBurst
    {
      get { return _inBurst; }
      set { _inBurst = value; }
    }

    private ulong _outRate = default(ulong);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"out_rate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong OutRate
    {
      get { return _outRate; }
      set { _outRate = value; }
    }

    private ulong _outBurst = default(ulong);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"out_burst", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong OutBurst
    {
      get { return _outBurst; }
      set { _outBurst = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: limit_bandwidth.proto
namespace IronFoundry.Warden.Protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LimitBandwidthRequest")]
  public partial class LimitBandwidthRequest : global::ProtoBuf.IExtensible
  {
    public LimitBandwidthRequest() {}
    
    private string _handle;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"handle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Handle
    {
      get { return _handle; }
      set { _handle = value; }
    }
    private ulong _rate;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"rate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong Rate
    {
      get { return _rate; }
      set { _rate = value; }
    }
    private ulong _burst;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"burst", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong Burst
    {
      get { return _burst; }
      set { _burst = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LimitBandwidthResponse")]
  public partial class LimitBandwidthResponse : global::ProtoBuf.IExtensible
  {
    public LimitBandwidthResponse() {}
    
    private ulong _rate;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"rate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong Rate
    {
      get { return _rate; }
      set { _rate = value; }
    }
    private ulong _burst;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"burst", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong Burst
    {
      get { return _burst; }
      set { _burst = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: limit_disk.proto
namespace IronFoundry.Warden.Protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LimitDiskRequest")]
  public partial class LimitDiskRequest : global::ProtoBuf.IExtensible
  {
    public LimitDiskRequest() {}
    
    private string _handle;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"handle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Handle
    {
      get { return _handle; }
      set { _handle = value; }
    }

    private ulong _blockLimit = default(ulong);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"block_limit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong BlockLimit
    {
      get { return _blockLimit; }
      set { _blockLimit = value; }
    }

    private ulong _block = default(ulong);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"block", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong Block
    {
      get { return _block; }
      set { _block = value; }
    }

    private ulong _blockSoft = default(ulong);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"block_soft", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong BlockSoft
    {
      get { return _blockSoft; }
      set { _blockSoft = value; }
    }

    private ulong _blockHard = default(ulong);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"block_hard", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong BlockHard
    {
      get { return _blockHard; }
      set { _blockHard = value; }
    }

    private ulong _inodeLimit = default(ulong);
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"inode_limit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong InodeLimit
    {
      get { return _inodeLimit; }
      set { _inodeLimit = value; }
    }

    private ulong _inode = default(ulong);
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"inode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong Inode
    {
      get { return _inode; }
      set { _inode = value; }
    }

    private ulong _inodeSoft = default(ulong);
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"inode_soft", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong InodeSoft
    {
      get { return _inodeSoft; }
      set { _inodeSoft = value; }
    }

    private ulong _inodeHard = default(ulong);
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"inode_hard", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong InodeHard
    {
      get { return _inodeHard; }
      set { _inodeHard = value; }
    }

    private ulong _byteLimit = default(ulong);
    [global::ProtoBuf.ProtoMember(30, IsRequired = false, Name=@"byte_limit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong ByteLimit
    {
      get { return _byteLimit; }
      set { _byteLimit = value; }
    }

    private ulong _byte = default(ulong);
    [global::ProtoBuf.ProtoMember(31, IsRequired = false, Name=@"byte", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong Byte
    {
      get { return _byte; }
      set { _byte = value; }
    }

    private ulong _byteSoft = default(ulong);
    [global::ProtoBuf.ProtoMember(32, IsRequired = false, Name=@"byte_soft", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong ByteSoft
    {
      get { return _byteSoft; }
      set { _byteSoft = value; }
    }

    private ulong _byteHard = default(ulong);
    [global::ProtoBuf.ProtoMember(33, IsRequired = false, Name=@"byte_hard", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong ByteHard
    {
      get { return _byteHard; }
      set { _byteHard = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LimitDiskResponse")]
  public partial class LimitDiskResponse : global::ProtoBuf.IExtensible
  {
    public LimitDiskResponse() {}
    

    private ulong _blockLimit = default(ulong);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"block_limit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong BlockLimit
    {
      get { return _blockLimit; }
      set { _blockLimit = value; }
    }

    private ulong _block = default(ulong);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"block", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong Block
    {
      get { return _block; }
      set { _block = value; }
    }

    private ulong _blockSoft = default(ulong);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"block_soft", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong BlockSoft
    {
      get { return _blockSoft; }
      set { _blockSoft = value; }
    }

    private ulong _blockHard = default(ulong);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"block_hard", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong BlockHard
    {
      get { return _blockHard; }
      set { _blockHard = value; }
    }

    private ulong _inodeLimit = default(ulong);
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"inode_limit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong InodeLimit
    {
      get { return _inodeLimit; }
      set { _inodeLimit = value; }
    }

    private ulong _inode = default(ulong);
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"inode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong Inode
    {
      get { return _inode; }
      set { _inode = value; }
    }

    private ulong _inodeSoft = default(ulong);
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"inode_soft", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong InodeSoft
    {
      get { return _inodeSoft; }
      set { _inodeSoft = value; }
    }

    private ulong _inodeHard = default(ulong);
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"inode_hard", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong InodeHard
    {
      get { return _inodeHard; }
      set { _inodeHard = value; }
    }

    private ulong _byteLimit = default(ulong);
    [global::ProtoBuf.ProtoMember(30, IsRequired = false, Name=@"byte_limit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong ByteLimit
    {
      get { return _byteLimit; }
      set { _byteLimit = value; }
    }

    private ulong _byte = default(ulong);
    [global::ProtoBuf.ProtoMember(31, IsRequired = false, Name=@"byte", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong Byte
    {
      get { return _byte; }
      set { _byte = value; }
    }

    private ulong _byteSoft = default(ulong);
    [global::ProtoBuf.ProtoMember(32, IsRequired = false, Name=@"byte_soft", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong ByteSoft
    {
      get { return _byteSoft; }
      set { _byteSoft = value; }
    }

    private ulong _byteHard = default(ulong);
    [global::ProtoBuf.ProtoMember(33, IsRequired = false, Name=@"byte_hard", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong ByteHard
    {
      get { return _byteHard; }
      set { _byteHard = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: limit_memory.proto
namespace IronFoundry.Warden.Protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LimitMemoryRequest")]
  public partial class LimitMemoryRequest : global::ProtoBuf.IExtensible
  {
    public LimitMemoryRequest() {}
    
    private string _handle;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"handle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Handle
    {
      get { return _handle; }
      set { _handle = value; }
    }

    private ulong _limitInBytes = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"limit_in_bytes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong LimitInBytes
    {
      get { return _limitInBytes; }
      set { _limitInBytes = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LimitMemoryResponse")]
  public partial class LimitMemoryResponse : global::ProtoBuf.IExtensible
  {
    public LimitMemoryResponse() {}
    

    private ulong _limitInBytes = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"limit_in_bytes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong LimitInBytes
    {
      get { return _limitInBytes; }
      set { _limitInBytes = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: link.proto
namespace IronFoundry.Warden.Protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LinkRequest")]
  public partial class LinkRequest : global::ProtoBuf.IExtensible
  {
    public LinkRequest() {}
    
    private string _handle;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"handle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Handle
    {
      get { return _handle; }
      set { _handle = value; }
    }
    private uint _jobId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"job_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint JobId
    {
      get { return _jobId; }
      set { _jobId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LinkResponse")]
  public partial class LinkResponse : global::ProtoBuf.IExtensible
  {
    public LinkResponse() {}
    

    private uint _exitStatus = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"exit_status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint ExitStatus
    {
      get { return _exitStatus; }
      set { _exitStatus = value; }
    }

    private string _stdout = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"stdout", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Stdout
    {
      get { return _stdout; }
      set { _stdout = value; }
    }

    private string _stderr = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"stderr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Stderr
    {
      get { return _stderr; }
      set { _stderr = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: list.proto
namespace IronFoundry.Warden.Protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ListRequest")]
  public partial class ListRequest : global::ProtoBuf.IExtensible
  {
    public ListRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ListResponse")]
  public partial class ListResponse : global::ProtoBuf.IExtensible
  {
    public ListResponse() {}
    
    private readonly global::System.Collections.Generic.List<string> _handles = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(1, Name=@"handles", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> Handles
    {
      get { return _handles; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: message.proto
namespace IronFoundry.Warden.Protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Message")]
  public partial class Message : global::ProtoBuf.IExtensible
  {
    public Message() {}
    
    private IronFoundry.Warden.Protocol.Message.Type _messageType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"message_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public IronFoundry.Warden.Protocol.Message.Type MessageType
    {
      get { return _messageType; }
      set { _messageType = value; }
    }
    private byte[] _payload;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"payload", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] Payload
    {
      get { return _payload; }
      set { _payload = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Type")]
    public enum Type
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error", Value=1)]
      Error = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Create", Value=11)]
      Create = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Stop", Value=12)]
      Stop = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Destroy", Value=13)]
      Destroy = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Info", Value=14)]
      Info = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Spawn", Value=21)]
      Spawn = 21,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Link", Value=22)]
      Link = 22,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Run", Value=23)]
      Run = 23,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Stream", Value=24)]
      Stream = 24,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NetIn", Value=31)]
      NetIn = 31,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NetOut", Value=32)]
      NetOut = 32,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CopyIn", Value=41)]
      CopyIn = 41,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CopyOut", Value=42)]
      CopyOut = 42,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LimitMemory", Value=51)]
      LimitMemory = 51,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LimitDisk", Value=52)]
      LimitDisk = 52,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LimitBandwidth", Value=53)]
      LimitBandwidth = 53,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Ping", Value=91)]
      Ping = 91,
            
      [global::ProtoBuf.ProtoEnum(Name=@"List", Value=92)]
      List = 92,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Echo", Value=93)]
      Echo = 93
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: net_in.proto
namespace IronFoundry.Warden.Protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NetInRequest")]
  public partial class NetInRequest : global::ProtoBuf.IExtensible
  {
    public NetInRequest() {}
    
    private string _handle;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"handle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Handle
    {
      get { return _handle; }
      set { _handle = value; }
    }

    private uint _hostPort = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"host_port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint HostPort
    {
      get { return _hostPort; }
      set { _hostPort = value; }
    }

    private uint _containerPort = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"container_port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint ContainerPort
    {
      get { return _containerPort; }
      set { _containerPort = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NetInResponse")]
  public partial class NetInResponse : global::ProtoBuf.IExtensible
  {
    public NetInResponse() {}
    
    private uint _hostPort;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"host_port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint HostPort
    {
      get { return _hostPort; }
      set { _hostPort = value; }
    }
    private uint _containerPort;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"container_port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ContainerPort
    {
      get { return _containerPort; }
      set { _containerPort = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: net_out.proto
namespace IronFoundry.Warden.Protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NetOutRequest")]
  public partial class NetOutRequest : global::ProtoBuf.IExtensible
  {
    public NetOutRequest() {}
    
    private string _handle;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"handle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Handle
    {
      get { return _handle; }
      set { _handle = value; }
    }

    private string _network = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"network", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Network
    {
      get { return _network; }
      set { _network = value; }
    }

    private uint _port = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Port
    {
      get { return _port; }
      set { _port = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NetOutResponse")]
  public partial class NetOutResponse : global::ProtoBuf.IExtensible
  {
    public NetOutResponse() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: ping.proto
namespace IronFoundry.Warden.Protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PingRequest")]
  public partial class PingRequest : global::ProtoBuf.IExtensible
  {
    public PingRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PingResponse")]
  public partial class PingResponse : global::ProtoBuf.IExtensible
  {
    public PingResponse() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: resource_limits.proto
namespace IronFoundry.Warden.Protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResourceLimits")]
  public partial class ResourceLimits : global::ProtoBuf.IExtensible
  {
    public ResourceLimits() {}
    

    private ulong _as = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"as", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong As
    {
      get { return _as; }
      set { _as = value; }
    }

    private ulong _core = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"core", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong Core
    {
      get { return _core; }
      set { _core = value; }
    }

    private ulong _cpu = default(ulong);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"cpu", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong Cpu
    {
      get { return _cpu; }
      set { _cpu = value; }
    }

    private ulong _data = default(ulong);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong Data
    {
      get { return _data; }
      set { _data = value; }
    }

    private ulong _fsize = default(ulong);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"fsize", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong Fsize
    {
      get { return _fsize; }
      set { _fsize = value; }
    }

    private ulong _locks = default(ulong);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"locks", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong Locks
    {
      get { return _locks; }
      set { _locks = value; }
    }

    private ulong _memlock = default(ulong);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"memlock", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong Memlock
    {
      get { return _memlock; }
      set { _memlock = value; }
    }

    private ulong _msgqueue = default(ulong);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"msgqueue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong Msgqueue
    {
      get { return _msgqueue; }
      set { _msgqueue = value; }
    }

    private ulong _nice = default(ulong);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"nice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong Nice
    {
      get { return _nice; }
      set { _nice = value; }
    }

    private ulong _nofile = default(ulong);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"nofile", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong Nofile
    {
      get { return _nofile; }
      set { _nofile = value; }
    }

    private ulong _nproc = default(ulong);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"nproc", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong Nproc
    {
      get { return _nproc; }
      set { _nproc = value; }
    }

    private ulong _rss = default(ulong);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"rss", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong Rss
    {
      get { return _rss; }
      set { _rss = value; }
    }

    private ulong _rtprio = default(ulong);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"rtprio", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong Rtprio
    {
      get { return _rtprio; }
      set { _rtprio = value; }
    }

    private ulong _sigpending = default(ulong);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"sigpending", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong Sigpending
    {
      get { return _sigpending; }
      set { _sigpending = value; }
    }

    private ulong _stack = default(ulong);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"stack", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong Stack
    {
      get { return _stack; }
      set { _stack = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: run.proto
// Note: requires additional types generated from: resource_limits.proto
namespace IronFoundry.Warden.Protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RunRequest")]
  public partial class RunRequest : global::ProtoBuf.IExtensible
  {
    public RunRequest() {}
    
    private string _handle;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"handle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Handle
    {
      get { return _handle; }
      set { _handle = value; }
    }
    private string _script;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"script", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Script
    {
      get { return _script; }
      set { _script = value; }
    }

    private bool _privileged = (bool)false;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"privileged", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool Privileged
    {
      get { return _privileged; }
      set { _privileged = value; }
    }

    private IronFoundry.Warden.Protocol.ResourceLimits _rlimits = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"rlimits", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public IronFoundry.Warden.Protocol.ResourceLimits Rlimits
    {
      get { return _rlimits; }
      set { _rlimits = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RunResponse")]
  public partial class RunResponse : global::ProtoBuf.IExtensible
  {
    public RunResponse() {}
    

    private uint _exitStatus = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"exit_status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint ExitStatus
    {
      get { return _exitStatus; }
      set { _exitStatus = value; }
    }

    private string _stdout = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"stdout", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Stdout
    {
      get { return _stdout; }
      set { _stdout = value; }
    }

    private string _stderr = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"stderr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Stderr
    {
      get { return _stderr; }
      set { _stderr = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: spawn.proto
// Note: requires additional types generated from: resource_limits.proto
namespace IronFoundry.Warden.Protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SpawnRequest")]
  public partial class SpawnRequest : global::ProtoBuf.IExtensible
  {
    public SpawnRequest() {}
    
    private string _handle;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"handle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Handle
    {
      get { return _handle; }
      set { _handle = value; }
    }
    private string _script;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"script", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Script
    {
      get { return _script; }
      set { _script = value; }
    }

    private bool _privileged = (bool)false;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"privileged", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool Privileged
    {
      get { return _privileged; }
      set { _privileged = value; }
    }

    private IronFoundry.Warden.Protocol.ResourceLimits _rlimits = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"rlimits", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public IronFoundry.Warden.Protocol.ResourceLimits Rlimits
    {
      get { return _rlimits; }
      set { _rlimits = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SpawnResponse")]
  public partial class SpawnResponse : global::ProtoBuf.IExtensible
  {
    public SpawnResponse() {}
    
    private uint _jobId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"job_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint JobId
    {
      get { return _jobId; }
      set { _jobId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: stop.proto
namespace IronFoundry.Warden.Protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StopRequest")]
  public partial class StopRequest : global::ProtoBuf.IExtensible
  {
    public StopRequest() {}
    
    private string _handle;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"handle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Handle
    {
      get { return _handle; }
      set { _handle = value; }
    }

    private bool _background = (bool)false;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"background", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool Background
    {
      get { return _background; }
      set { _background = value; }
    }

    private bool _kill = (bool)false;
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"kill", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool Kill
    {
      get { return _kill; }
      set { _kill = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StopResponse")]
  public partial class StopResponse : global::ProtoBuf.IExtensible
  {
    public StopResponse() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: stream.proto
namespace IronFoundry.Warden.Protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StreamRequest")]
  public partial class StreamRequest : global::ProtoBuf.IExtensible
  {
    public StreamRequest() {}
    
    private string _handle;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"handle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Handle
    {
      get { return _handle; }
      set { _handle = value; }
    }
    private uint _jobId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"job_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint JobId
    {
      get { return _jobId; }
      set { _jobId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StreamResponse")]
  public partial class StreamResponse : global::ProtoBuf.IExtensible
  {
    public StreamResponse() {}
    

    private string _name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Name
    {
      get { return _name; }
      set { _name = value; }
    }

    private string _data = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Data
    {
      get { return _data; }
      set { _data = value; }
    }

    private uint _exitStatus = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"exit_status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint ExitStatus
    {
      get { return _exitStatus; }
      set { _exitStatus = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
