//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudFoundry.Net.Vmc.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CloudFoundry.Net.Vmc.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///{0}
        ///For support visit {1}
        ///
        ///Target:   {2} ({3})
        ///Client:   v{4}.
        /// </summary>
        public static string VcapClient_InfoDisplay_1_Fmt {
            get {
                return ResourceManager.GetString("VcapClient_InfoDisplay_1_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User:     {0}.
        /// </summary>
        public static string VcapClient_InfoDisplay_2_Fmt {
            get {
                return ResourceManager.GetString("VcapClient_InfoDisplay_2_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage:    Memory   ({0} of {1} total)
        ///          Services ({2} of {3} total)
        ///          Apps     ({4} of {5} total).
        /// </summary>
        public static string VcapClient_InfoDisplay_3_Fmt {
            get {
                return ResourceManager.GetString("VcapClient_InfoDisplay_3_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set a target..
        /// </summary>
        public static string VcapClient_PleaseSetTarget_Message {
            get {
                return ResourceManager.GetString("VcapClient_PleaseSetTarget_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succesfully targeted [{0}].
        /// </summary>
        public static string VcapClient_TargetDisplay_Fmt {
            get {
                return ResourceManager.GetString("VcapClient_TargetDisplay_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}].
        /// </summary>
        public static string VcapClient_TargetNoSuccessDisplay_Fmt {
            get {
                return ResourceManager.GetString("VcapClient_TargetNoSuccessDisplay_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url required..
        /// </summary>
        public static string VcapClient_UrlRequired_Message {
            get {
                return ResourceManager.GetString("VcapClient_UrlRequired_Message", resourceCulture);
            }
        }
    }
}
