//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IronFoundry.Dea.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IronFoundry.Dea.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent detected error in NATS..
        /// </summary>
        internal static string Agent_ErrorDetectedInNats_Message {
            get {
                return ResourceManager.GetString("Agent_ErrorDetectedInNats_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent.Stop(): Tasks completed..
        /// </summary>
        internal static string Agent_TasksCompletedInStop_Message {
            get {
                return ResourceManager.GetString("Agent_TasksCompletedInStop_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent.Stop(): Waiting for tasks..
        /// </summary>
        internal static string Agent_WaitingForTasksInStop_Message {
            get {
                return ResourceManager.GetString("Agent_WaitingForTasksInStop_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting reconnect to server..
        /// </summary>
        internal static string NatsMessagingProvider_AttemptingReconnect_Message {
            get {
                return ResourceManager.GetString("NatsMessagingProvider_AttemptingReconnect_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid attempt to reconnect twice..
        /// </summary>
        internal static string NatsMessagingProvider_AttemptingReconnectTwice_Message {
            get {
                return ResourceManager.GetString("NatsMessagingProvider_AttemptingReconnectTwice_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid attempt to stop twice..
        /// </summary>
        internal static string NatsMessagingProvider_AttemptingStopTwice_Message {
            get {
                return ResourceManager.GetString("NatsMessagingProvider_AttemptingStopTwice_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read from network stream..
        /// </summary>
        internal static string NatsMessagingProvider_CantReadFromStream_Message {
            get {
                return ResourceManager.GetString("NatsMessagingProvider_CantReadFromStream_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not reconnect to server..
        /// </summary>
        internal static string NatsMessagingProvider_CouldNotReconnect_Message {
            get {
                return ResourceManager.GetString("NatsMessagingProvider_CouldNotReconnect_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client disconnected from server..
        /// </summary>
        internal static string NatsMessagingProvider_Disconnected_Message {
            get {
                return ResourceManager.GetString("NatsMessagingProvider_Disconnected_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully reconnected to server..
        /// </summary>
        internal static string NatsMessagingProvider_ReconnectSuccess_Message {
            get {
                return ResourceManager.GetString("NatsMessagingProvider_ReconnectSuccess_Message", resourceCulture);
            }
        }
    }
}
