//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IronFoundry.Dea.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IronFoundry.Dea.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEA.
        /// </summary>
        internal static string Agent_DEAComponentType {
            get {
                return ResourceManager.GetString("Agent_DEAComponentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://{0}:{1}/droplets/.
        /// </summary>
        internal static string Agent_Droplets_Fmt {
            get {
                return ResourceManager.GetString("Agent_Droplets_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent detected error in NATS..
        /// </summary>
        internal static string Agent_ErrorDetectedInNats_Message {
            get {
                return ResourceManager.GetString("Agent_ErrorDetectedInNats_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance exited: {0}.
        /// </summary>
        internal static string Agent_InstanceExited_Fmt {
            get {
                return ResourceManager.GetString("Agent_InstanceExited_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This DEA does not support non-ASP.NET frameworks!.
        /// </summary>
        internal static string Agent_NonAspDotNet_Message {
            get {
                return ResourceManager.GetString("Agent_NonAspDotNet_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessDeaDiscover Msg: {0} Reply: {1}.
        /// </summary>
        internal static string Agent_ProcessDeaDiscover_Fmt {
            get {
                return ResourceManager.GetString("Agent_ProcessDeaDiscover_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessDeaDiscover: unsupported runtime &apos;{0}&apos;.
        /// </summary>
        internal static string Agent_ProcessDeaDiscoverUnsupportedRuntime_Fmt {
            get {
                return ResourceManager.GetString("Agent_ProcessDeaDiscoverUnsupportedRuntime_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessDeaFindDroplet: {0}.
        /// </summary>
        internal static string Agent_ProcessDeaFindDroplet_Fmt {
            get {
                return ResourceManager.GetString("Agent_ProcessDeaFindDroplet_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessDeaStart: {0}.
        /// </summary>
        internal static string Agent_ProcessDeaStart_Fmt {
            get {
                return ResourceManager.GetString("Agent_ProcessDeaStart_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No web instance created for application with name &apos;{0}&apos;..
        /// </summary>
        internal static string Agent_ProcessDeaStartNoBindingAvailable {
            get {
                return ResourceManager.GetString("Agent_ProcessDeaStartNoBindingAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessDeaStatus Msg: {0} Reply: {1}.
        /// </summary>
        internal static string Agent_ProcessDeaStatus_Fmt {
            get {
                return ResourceManager.GetString("Agent_ProcessDeaStatus_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessDeaStop: {0}.
        /// </summary>
        internal static string Agent_ProcessDeaStop_Fmt {
            get {
                return ResourceManager.GetString("Agent_ProcessDeaStop_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessDeaUpdate: {0}.
        /// </summary>
        internal static string Agent_ProcessDeaUpdate_Fmt {
            get {
                return ResourceManager.GetString("Agent_ProcessDeaUpdate_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessDropletStatus Msg: {0} Reply: {1}.
        /// </summary>
        internal static string Agent_ProcessDropletStatus_Fmt {
            get {
                return ResourceManager.GetString("Agent_ProcessDropletStatus_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessHealthManagerStart Msg: {0} Reply: {1}.
        /// </summary>
        internal static string Agent_ProcessHealthManagerStart_Fmt {
            get {
                return ResourceManager.GetString("Agent_ProcessHealthManagerStart_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessRouterStart Msg: {0} Reply: {1}.
        /// </summary>
        internal static string Agent_ProcessRouterStart_Fmt {
            get {
                return ResourceManager.GetString("Agent_ProcessRouterStart_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent shutdown complete..
        /// </summary>
        internal static string Agent_Shutdown_Message {
            get {
                return ResourceManager.GetString("Agent_Shutdown_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent shutting down ....
        /// </summary>
        internal static string Agent_ShuttingDown_Message {
            get {
                return ResourceManager.GetString("Agent_ShuttingDown_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped instance: {0}.
        /// </summary>
        internal static string Agent_StoppedInstance_Fmt {
            get {
                return ResourceManager.GetString("Agent_StoppedInstance_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping instance: {0}.
        /// </summary>
        internal static string Agent_StoppingInstance_Fmt {
            get {
                return ResourceManager.GetString("Agent_StoppingInstance_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent.Stop(): Tasks completed..
        /// </summary>
        internal static string Agent_TasksCompletedInStop_Message {
            get {
                return ResourceManager.GetString("Agent_TasksCompletedInStop_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent.Stop(): Waiting for tasks..
        /// </summary>
        internal static string Agent_WaitingForTasksInStop_Message {
            get {
                return ResourceManager.GetString("Agent_WaitingForTasksInStop_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password &apos;{0}&apos; sent to files service..
        /// </summary>
        internal static string FilesServiceValidator_InvalidPassword_Fmt {
            get {
                return ResourceManager.GetString("FilesServiceValidator_InvalidPassword_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username &apos;{0}&apos; sent to files service..
        /// </summary>
        internal static string FilesServiceValidator_InvalidUser_Fmt {
            get {
                return ResourceManager.GetString("FilesServiceValidator_InvalidUser_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iron Foundry DEA Files Service.
        /// </summary>
        internal static string FilesWinService_ServiceName {
            get {
                return ResourceManager.GetString("FilesWinService_ServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HealthzProvider.GetHealthz() called..
        /// </summary>
        internal static string HealthzProvider_GetHealthzCalled_Message {
            get {
                return ResourceManager.GetString("HealthzProvider_GetHealthzCalled_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error setting up Event Log logger!.
        /// </summary>
        internal static string InternalLog_ErrorInSettingUpEventLogger_Message {
            get {
                return ResourceManager.GetString("InternalLog_ErrorInSettingUpEventLogger_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iron Foundry DEA Monitoring Service.
        /// </summary>
        internal static string MonitoringWinService_ServiceName {
            get {
                return ResourceManager.GetString("MonitoringWinService_ServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find appcmd.exe in IIS installation directory..
        /// </summary>
        internal static string ValidationWinService_AppCmdNotFound_Message {
            get {
                return ResourceManager.GetString("ValidationWinService_AppCmdNotFound_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VarzProvdider.GetVarzJson():
        ///{0}.
        /// </summary>
        internal static string VarzProvider_GetVarzJson_Fmt {
            get {
                return ResourceManager.GetString("VarzProvider_GetVarzJson_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error closing WCF host! Message: {0}.
        /// </summary>
        internal static string WcfService_ErrorClosingHost_Fmt {
            get {
                return ResourceManager.GetString("WcfService_ErrorClosingHost_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WCF ServiceHost &apos;{0}&apos; NOT configured to run..
        /// </summary>
        internal static string WcfService_NotConfiguredToRun_Fmt {
            get {
                return ResourceManager.GetString("WcfService_NotConfiguredToRun_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting WCF ServiceHost &apos;{0}&apos;.
        /// </summary>
        internal static string WcfService_StartingHost_Fmt {
            get {
                return ResourceManager.GetString("WcfService_StartingHost_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping WCF ServiceHost &apos;{0}&apos;.
        /// </summary>
        internal static string WcfService_StoppingHost_Fmt {
            get {
                return ResourceManager.GetString("WcfService_StoppingHost_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web application already exists &apos;{0}&apos;.
        /// </summary>
        internal static string WebServerAdministrationProvider_AppAlreadyExists_Fmt {
            get {
                return ResourceManager.GetString("WebServerAdministrationProvider_AppAlreadyExists_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;appcmd.exe {0}&apos; failed: {1}.
        /// </summary>
        internal static string WebServerAdministrationProvider_AppCmdFailed_Fmt {
            get {
                return ResourceManager.GetString("WebServerAdministrationProvider_AppCmdFailed_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid managed runtime version: {0}.
        /// </summary>
        internal static string WebServerAdministrationProvider_InvalidManagedRuntimeVersion_Fmt {
            get {
                return ResourceManager.GetString("WebServerAdministrationProvider_InvalidManagedRuntimeVersion_Fmt", resourceCulture);
            }
        }
    }
}
