//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IronFoundry.Warden.IisHost.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IronFoundry.Warden.IisHost.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;UTF-8&apos; ?&gt;
        ///&lt;configuration&gt;
        ///    &lt;configSections&gt;
        ///        &lt;sectionGroup name=&apos;system.applicationHost&apos;&gt;
        ///            &lt;section name=&apos;applicationPools&apos; allowDefinition=&apos;AppHostOnly&apos; /&gt;
        ///            &lt;section name=&apos;listenerAdapters&apos; allowDefinition=&apos;AppHostOnly&apos; /&gt;
        ///            &lt;section name=&apos;log&apos; allowDefinition=&apos;AppHostOnly&apos; /&gt;
        ///            &lt;section name=&apos;sites&apos; allowDefinition=&apos;AppHostOnly&apos; /&gt;
        ///            &lt;section name=&apos;webLimits&apos; allowDefinition=&apos;AppHostOnly&apos; /&gt;
        ///        &lt;/sect [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AppHostAspNet {
            get {
                return ResourceManager.GetString("AppHostAspNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;UTF-8&apos; ?&gt;
        ///&lt;configuration&gt;
        ///    &lt;configSections&gt;
        ///        &lt;sectionGroup name=&apos;system.applicationHost&apos;&gt;
        ///            &lt;section name=&apos;applicationPools&apos; allowDefinition=&apos;AppHostOnly&apos; /&gt;
        ///            &lt;section name=&apos;listenerAdapters&apos; allowDefinition=&apos;AppHostOnly&apos; /&gt;
        ///            &lt;section name=&apos;log&apos; allowDefinition=&apos;AppHostOnly&apos; /&gt;
        ///            &lt;section name=&apos;sites&apos; allowDefinition=&apos;AppHostOnly&apos; /&gt;
        ///            &lt;section name=&apos;webLimits&apos; allowDefinition=&apos;AppHostOnly&apos; /&gt;
        ///        &lt;/sect [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AppHostStaticFiles {
            get {
                return ResourceManager.GetString("AppHostStaticFiles", resourceCulture);
            }
        }
    }
}
