//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IronFoundry.Bosh.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IronFoundry.Bosh.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create object {0}/{1}.
        /// </summary>
        public static string BlobstoreClient_CouldNotCreateObject_Fmt {
            get {
                return ResourceManager.GetString("BlobstoreClient_CouldNotCreateObject_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete object {0}/{1}.
        /// </summary>
        public static string BlobstoreClient_CouldNotDeleteObject_Fmt {
            get {
                return ResourceManager.GetString("BlobstoreClient_CouldNotDeleteObject_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not fetch object {0}/{1}.
        /// </summary>
        public static string BlobstoreClient_CouldNotFetchObject_Fmt {
            get {
                return ResourceManager.GetString("BlobstoreClient_CouldNotFetchObject_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local file &apos;{0}&apos; does not exist..
        /// </summary>
        public static string BlobstoreClient_LocalFileDoesNotExist_Fmt {
            get {
                return ResourceManager.GetString("BlobstoreClient_LocalFileDoesNotExist_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown plugin in Blobstore client factory: {0}.
        /// </summary>
        public static string BlobstoreClientFactory_UnknownPlugin_Fmt {
            get {
                return ResourceManager.GetString("BlobstoreClientFactory_UnknownPlugin_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message: {0}.
        /// </summary>
        public static string BoshAgent_AgentMessage_Fmt {
            get {
                return ResourceManager.GetString("BoshAgent_AgentMessage_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception handling method &apos;{0}&apos;!.
        /// </summary>
        public static string BoshAgent_ExceptionHandlingMethod_Fmt {
            get {
                return ResourceManager.GetString("BoshAgent_ExceptionHandlingMethod_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing handler for method &apos;{0}&apos;!.
        /// </summary>
        public static string BoshAgent_MissingHandlerForMethod_Fmt {
            get {
                return ResourceManager.GetString("BoshAgent_MissingHandlerForMethod_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing reply_to in: {0}.
        /// </summary>
        public static string BoshAgent_MissingReplyTo_Fmt {
            get {
                return ResourceManager.GetString("BoshAgent_MissingReplyTo_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reply_to: {0}: payload: {1}.
        /// </summary>
        public static string BoshAgent_ResponseDebug_Fmt {
            get {
                return ResourceManager.GetString("BoshAgent_ResponseDebug_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message size {0} &gt; NATS_MAX_PAYLOAD_SIZE {1}.
        /// </summary>
        public static string BoshAgent_ResponseJsonTooLarge_Fmt {
            get {
                return ResourceManager.GetString("BoshAgent_ResponseJsonTooLarge_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to reconnect to NATS after {0} retries, exiting....
        /// </summary>
        public static string BoshAgent_UnableToConnectAfterRetries_Fmt {
            get {
                return ResourceManager.GetString("BoshAgent_UnableToConnectAfterRetries_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compile package failure (exit code: {0}).
        /// </summary>
        public static string CompilePackage_CompilePackageFailure_Fmt {
            get {
                return ResourceManager.GetString("CompilePackage_CompilePackageFailure_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiling {0} {1}.
        /// </summary>
        public static string CompilePackage_CompilingPackage_Fmt {
            get {
                return ResourceManager.GetString("CompilePackage_CompilingPackage_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting dir:{0}.
        /// </summary>
        public static string CompilePackage_ErrorDeleting_Fmt {
            get {
                return ResourceManager.GetString("CompilePackage_ErrorDeleting_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing Dependencies.
        /// </summary>
        public static string CompilePackage_InstallingDependencies_Message {
            get {
                return ResourceManager.GetString("CompilePackage_InstallingDependencies_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing dependency: {0} {1}.
        /// </summary>
        public static string CompilePackage_InstallingDependency_Fmt {
            get {
                return ResourceManager.GetString("CompilePackage_InstallingDependency_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing {0} {1}.
        /// </summary>
        public static string CompilePackage_Packing_Fmt {
            get {
                return ResourceManager.GetString("CompilePackage_Packing_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded {0} {1} (sha1: {2}, blobstore_id: {3}).
        /// </summary>
        public static string CompilePackage_Uploaded_Fmt {
            get {
                return ResourceManager.GetString("CompilePackage_Uploaded_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown drain type {0}.
        /// </summary>
        public static string Drain_UnknownDrainType_Fmt {
            get {
                return ResourceManager.GetString("Drain_UnknownDrainType_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heartbeat requires agentID..
        /// </summary>
        public static string Heartbeat_RequiresAgentID_Message {
            get {
                return ResourceManager.GetString("Heartbeat_RequiresAgentID_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;unattend xmlns=&quot;urn:schemas-microsoft-com:unattend&quot;&gt;
        ///  &lt;settings pass=&quot;specialize&quot;&gt;
        ///    &lt;component name=&quot;Microsoft-Windows-Shell-Setup&quot; processorArchitecture=&quot;amd64&quot; publicKeyToken=&quot;31bf3856ad364e35&quot; language=&quot;neutral&quot; versionScope=&quot;nonSxS&quot; xmlns:wcm=&quot;http://schemas.microsoft.com/WMIConfig/2002/State&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///      &lt;ComputerName&gt;COMPUTERNAME&lt;/ComputerName&gt;
        ///      &lt;ProductKey&gt;YC6KT-GKW9T-YTKYR-T4X34-R7VHC&lt;/ProductKey&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string UnattendXML {
            get {
                return ResourceManager.GetString("UnattendXML", resourceCulture);
            }
        }
    }
}
