//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IronFoundry.Bosh.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IronFoundry.Bosh.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message: {0}.
        /// </summary>
        internal static string BoshAgent_AgentMessage_Fmt {
            get {
                return ResourceManager.GetString("BoshAgent_AgentMessage_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception handling method &apos;{0}&apos;!.
        /// </summary>
        internal static string BoshAgent_ExceptionHandlingMethod_Fmt {
            get {
                return ResourceManager.GetString("BoshAgent_ExceptionHandlingMethod_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing handler for method &apos;{0}&apos;!.
        /// </summary>
        internal static string BoshAgent_MissingHandlerForMethod_Fmt {
            get {
                return ResourceManager.GetString("BoshAgent_MissingHandlerForMethod_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing reply_to in: {0}.
        /// </summary>
        internal static string BoshAgent_MissingReplyTo_Fmt {
            get {
                return ResourceManager.GetString("BoshAgent_MissingReplyTo_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reply_to: {0}: payload: {1}.
        /// </summary>
        internal static string BoshAgent_ResponseDebug_Fmt {
            get {
                return ResourceManager.GetString("BoshAgent_ResponseDebug_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message size {0} &gt; NATS_MAX_PAYLOAD_SIZE {1}.
        /// </summary>
        internal static string BoshAgent_ResponseJsonTooLarge_Fmt {
            get {
                return ResourceManager.GetString("BoshAgent_ResponseJsonTooLarge_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to reconnect to NATS after {0} retries, exiting....
        /// </summary>
        internal static string BoshAgent_UnableToConnectAfterRetries_Fmt {
            get {
                return ResourceManager.GetString("BoshAgent_UnableToConnectAfterRetries_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heartbeat requires agentID..
        /// </summary>
        internal static string Heartbeat_RequiresAgentID_Message {
            get {
                return ResourceManager.GetString("Heartbeat_RequiresAgentID_Message", resourceCulture);
            }
        }
    }
}
