//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudFoundry.Net.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CloudFoundry.Net.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application &apos;{0}&apos; already exists..
        /// </summary>
        public static string AppsHelper_PushApplicationExists_Fmt {
            get {
                return ResourceManager.GetString("AppsHelper_PushApplicationExists_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email: .
        /// </summary>
        public static string Vmc_EmailPrompt_Text {
            get {
                return ResourceManager.GetString("Vmc_EmailPrompt_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///{0}
        ///For support visit {1}
        ///
        ///Target:   {2} ({3})
        ///Client:   v{4}.
        /// </summary>
        public static string Vmc_InfoDisplay_1_Fmt {
            get {
                return ResourceManager.GetString("Vmc_InfoDisplay_1_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User:     {0}.
        /// </summary>
        public static string Vmc_InfoDisplay_2_Fmt {
            get {
                return ResourceManager.GetString("Vmc_InfoDisplay_2_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage:    Memory   ({0} of {1} total)
        ///          Services ({2} of {3} total)
        ///          Apps     ({4} of {5} total).
        /// </summary>
        public static string Vmc_InfoDisplay_3_Fmt {
            get {
                return ResourceManager.GetString("Vmc_InfoDisplay_3_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem with login to [{0}] Exception:{1}.
        /// </summary>
        public static string Vmc_LoginError_Fmt {
            get {
                return ResourceManager.GetString("Vmc_LoginError_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem with login to [{0}] invalid account or password..
        /// </summary>
        public static string Vmc_LoginFail_Fmt {
            get {
                return ResourceManager.GetString("Vmc_LoginFail_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Required.
        /// </summary>
        public static string Vmc_LoginRequired_Message {
            get {
                return ResourceManager.GetString("Vmc_LoginRequired_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully logged into [{0}].
        /// </summary>
        public static string Vmc_LoginSuccess_Fmt {
            get {
                return ResourceManager.GetString("Vmc_LoginSuccess_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need a valid email..
        /// </summary>
        public static string Vmc_NeedEmailPrompt_Text {
            get {
                return ResourceManager.GetString("Vmc_NeedEmailPrompt_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need a password..
        /// </summary>
        public static string Vmc_NeedPasswordPrompt_Text {
            get {
                return ResourceManager.GetString("Vmc_NeedPasswordPrompt_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No content returned for request..
        /// </summary>
        public static string Vmc_NoContentReturned_Text {
            get {
                return ResourceManager.GetString("Vmc_NoContentReturned_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password: .
        /// </summary>
        public static string Vmc_PasswordPrompt_Text {
            get {
                return ResourceManager.GetString("Vmc_PasswordPrompt_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set a target..
        /// </summary>
        public static string Vmc_PleaseSetTarget_Message {
            get {
                return ResourceManager.GetString("Vmc_PleaseSetTarget_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succesfully targeted [{0}].
        /// </summary>
        public static string Vmc_TargetDisplay_Fmt {
            get {
                return ResourceManager.GetString("Vmc_TargetDisplay_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}].
        /// </summary>
        public static string Vmc_TargetNoSuccessDisplay_Fmt {
            get {
                return ResourceManager.GetString("Vmc_TargetNoSuccessDisplay_Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url required..
        /// </summary>
        public static string Vmc_UrlRequired_Message {
            get {
                return ResourceManager.GetString("Vmc_UrlRequired_Message", resourceCulture);
            }
        }
    }
}
